(()=>{
 const panel=document.querySelector('#chat-panel'),launch=document.querySelector('.chat-launcher');if(!panel||!launch)return;
 const log=panel.querySelector('.chat-log'),form=panel.querySelector('form'),input=panel.querySelector('textarea'),send=form.querySelector('button'),status=panel.querySelector('#chat-status');let live=false,busy=false,history=[],controller;
 const guides={start:'Start with one process that takes too long or requires repeated handovers. NCAISP can assess your systems and data, identify opportunities and agree a focused first project. Book an AI Strategy Session using the link below.',agents:'A specialised AI agent can retrieve approved knowledge, use permitted tools and help with a defined role such as research, support or operations. Important actions can require human approval. NCAISP also connects agents into wider workflows.',cost:'Pricing is scoped to the process, integrations, data and support required. We do not publish fixed prices or promise guaranteed results. A strategy session is the next step to discuss an appropriate scope.'};
 function add(text,role){const p=document.createElement('p');p.className='chat-message '+role;p.textContent=text;log.appendChild(p);log.scrollTop=log.scrollHeight;return p}
 function controls(){input.disabled=!live||busy;send.disabled=!live||busy;panel.querySelectorAll('[data-guide]').forEach(b=>b.disabled=busy)}
 function close(){panel.close();launch.focus()}
 launch.addEventListener('click',async()=>{panel.showModal();panel.querySelector('.chat-close').focus();try{const r=await fetch('/api/chat/status',{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();live=data.ready===true}catch{live=false}panel.querySelector('#chat-mode').textContent=live?'Aileen · AI assistant':'Aileen · Website guide';panel.querySelector('#chat-disclosure').textContent=live?'Ask me about NCAISP and how AI could help your business.':'Choose a topic to explore our services. Free-text chat will be available once connected.';status.textContent=live?'Ask about our capabilities, approach or use cases.':'Choose a topic above, or book a strategy session.';controls()});
 panel.querySelector('.chat-close').addEventListener('click',close);panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});
 panel.querySelector('#chat-book').addEventListener('click',()=>panel.close());
 panel.querySelectorAll('[data-guide]').forEach(b=>b.addEventListener('click',()=>{if(live){input.value=b.textContent;form.requestSubmit()}else{add(b.textContent,'user');add(guides[b.dataset.guide],'assistant')}}));
 panel.querySelector('.chat-clear').addEventListener('click',()=>{controller?.abort();history=[];log.replaceChildren();add('Conversation cleared. What would you like to explore?','assistant')});
 input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!busy&&live)form.requestSubmit()}});
 form.addEventListener('submit',async e=>{e.preventDefault();const question=input.value.trim();if(!question||busy||!live)return;busy=true;controls();add(question,'user');input.value='';status.textContent='Thinking…';controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),35000);try{const messages=[...history,{role:'user',content:question}].slice(-8);const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages}),signal:controller.signal});const data=await r.json();if(!r.ok||typeof data.reply!=='string')throw Error(data.error||'Chat is unavailable. Please try again or book a session.');add(data.reply,'assistant');history=[...messages,{role:'assistant',content:data.reply}].slice(-8);status.textContent=''}catch(error){status.textContent=error.name==='AbortError'?'Request cancelled or timed out. You can try again.':error.message;input.value=question}finally{clearTimeout(timeout);busy=false;controls();input.focus()}});
})();
